name: Docker Image CI

on:
  push:
    branches: [ "toACR" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: webappfordemo.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    #- name: Set up Docker Buildx ###for building on multi archetecure
    #  uses: docker/setup-buildx-action@
    - name: Stright up Build
      run: docker build -t thewebappcontainer:latest .
      
      
    - name: ARC Push
      run: docker push webappfordemo.azurecr.io/thewebappcontainer:latest #$(date +%s)

   # - name: Build and push
    #  uses: docker/build-push-action@v3.0.0
     # with:
      #  registry: webappfordemo.azurecr.io
       # context: .
        #file: ./Dockerfile
        #push: true
        #tags: webappfordemo/webappfordemo:latest #$(date +%s)
