name: Docker Image CI

on:
  push:
    branches: [ "toACR" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: ARC Login 
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: webappfordemo.azurecr.io
          # Username used to log against the Docker registry
          username: ${{ secrets.ACR_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.ACR_PASSWORD }}
      
     # - name: Set up Docker Buildx ###for building on multi archetecure
      #  uses: docker/setup-buildx-action@v2.0.0
          
      #- name: ARC Build
       # run: docker build https://raw.githubusercontent.com/aaaboulmagd/WebAppForDemos/toACR/Dockerfile?token=GHSAT0AAAAAABVLUPMYM744OKGW7EUJETGCYVGG4EA -t webappfordemo/thewebappcontainer:latest
      
      - name: ARC Push
        run: docker push webappfordemo:latest #$(date +%s)
     # - name: Build and push
      #  uses: docker/build-push-action@v2
       # with:
        #  registry: webappfordemo.azurecr.io
         # context: .
          #file: ./Dockerfile
        #  push: true
         # tags: webappfordemo:latest #$(date +%s)
          
